### ISSUE TITLE
Regarding number of epoch

### ISSUE THREAD

**Issue by shubhamgpt007** [PaulCCCCCCH/Multimodal-Categorization-of-Crisis-Events-in-Social-Media#4]
Hi, 
Thanks for the great work. I was not able to figure out that for how many number of epochs you ran the model. Can you provide that number and mention material where I can check.

**Comment by PaulCCCCCCH** [comment]
Hi, thanks for reaching out.

Sorry for not documenting that. I remember it did not take the model more than a few hours to converge with my setting. I think the 40 epochs in the `train.sh` is a good number to get the final results.

**Comment by shubhamgpt007** [comment]
Hi Paul,
Thanks for your reply. When i am running model for 40 epochs then not getting the same accuracy which is reported in the paper. I have seen in the code with argument section and default number of epochs is mentioned as 300. Can you please one more time verify that is it 40 or 300?
Again thanks for your time.

**Comment by PaulCCCCCCH** [comment]
300 epochs is way too much and I don't think training would take that long. If you monitor the accuracy as you train, the model should converge with a few dozens of epochs.

One thing that I should have documented is, you have to set `consistent-only` parameter to `true`, otherwise the model won't converge to the accuracy mentioned in the paper. 

Also, I remember the paper mentioned they merged some of the labels in task two, and you can apply that setting by passing  `--task=task2_merged`.

**Comment by kliean** [comment]
Hello, I would like to know how this dataset is split and why the distribution of the split data is different from the official one：https://crisisnlp.qcri.org/crisismmd
